
import org.json.JSONObject;
import util.TokenUtil;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class MyProfileFrame extends javax.swing.JFrame {
    private JSONObject userInfo;

    /**
     * Creates new form MyProfileFrame
     */
    public MyProfileFrame() {
        initComponents();
        loadUserInfo();
    }
    
    private void loadUserInfo() {
        try {

            userInfo = TokenUtil.loadUserInfo();
            System.out.println("userInfo: " + userInfo);

            if (userInfo != null) {
//                lblId.setText("아이디: " + userInfo.getString("userId"));
                lblName.setText("닉네임: " + userInfo.getString("userName"));
                lblPhone.setText("전화번호: " + userInfo.getString("number"));
                
                // 디버깅 출력
                
                System.out.println("lblName 텍스트: " + lblName.getText());
                System.out.println("lblPhone 텍스트: " + lblPhone.getText());
            } else {
                System.out.println("userInfo가 null입니다.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogName = new javax.swing.JDialog();
        lblNameBefore = new javax.swing.JLabel();
        txtNameBefore = new javax.swing.JTextField();
        lblNameAfter = new javax.swing.JLabel();
        txtNameAfter = new javax.swing.JTextField();
        btnNameUpd = new javax.swing.JButton();
        lblNameUpd = new javax.swing.JLabel();
        jDialogPhone = new javax.swing.JDialog();
        lblPhoneAfter = new javax.swing.JLabel();
        txtPhoneAfter = new javax.swing.JTextField();
        btnPhoneUpd = new javax.swing.JButton();
        lblPhoneBefore = new javax.swing.JLabel();
        lblPhoneUpd = new javax.swing.JLabel();
        txtPhoneBefore = new javax.swing.JTextField();
        jDialogDel = new javax.swing.JDialog();
        lblDel = new javax.swing.JLabel();
        btnDelYes = new javax.swing.JButton();
        btnDelNo = new javax.swing.JButton();
        jPaneHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        BookmarkAndReview = new javax.swing.JTabbedPane();
        jPanelBookmark = new javax.swing.JPanel();
        jPanelReview = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();

        lblNameBefore.setText("기존");

        txtNameBefore.setText("홍길동");

        lblNameAfter.setText("변경");

        btnNameUpd.setText("변경");

        lblNameUpd.setText("닉네임");

        javax.swing.GroupLayout jDialogNameLayout = new javax.swing.GroupLayout(jDialogName.getContentPane());
        jDialogName.getContentPane().setLayout(jDialogNameLayout);
        jDialogNameLayout.setHorizontalGroup(
            jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNameLayout.createSequentialGroup()
                .addGroup(jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNameLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDialogNameLayout.createSequentialGroup()
                                    .addComponent(lblNameAfter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNameAfter))
                                .addGroup(jDialogNameLayout.createSequentialGroup()
                                    .addComponent(lblNameBefore)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNameBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogNameLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnNameUpd))))
                    .addGroup(jDialogNameLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblNameUpd)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialogNameLayout.setVerticalGroup(
            jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNameLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblNameUpd)
                .addGap(18, 18, 18)
                .addGroup(jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameBefore)
                    .addComponent(txtNameBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameAfter)
                    .addComponent(txtNameAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNameUpd)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        lblPhoneAfter.setText("변경");

        btnPhoneUpd.setText("변경");

        lblPhoneBefore.setText("기존");

        lblPhoneUpd.setText("전화번호");

        txtPhoneBefore.setText("010-0000-0000");

        javax.swing.GroupLayout jDialogPhoneLayout = new javax.swing.GroupLayout(jDialogPhone.getContentPane());
        jDialogPhone.getContentPane().setLayout(jDialogPhoneLayout);
        jDialogPhoneLayout.setHorizontalGroup(
            jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPhoneLayout.createSequentialGroup()
                .addGroup(jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogPhoneLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDialogPhoneLayout.createSequentialGroup()
                                    .addComponent(lblPhoneAfter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPhoneAfter))
                                .addGroup(jDialogPhoneLayout.createSequentialGroup()
                                    .addComponent(lblPhoneBefore)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPhoneBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogPhoneLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnPhoneUpd))))
                    .addGroup(jDialogPhoneLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblPhoneUpd)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialogPhoneLayout.setVerticalGroup(
            jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPhoneLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblPhoneUpd)
                .addGap(18, 18, 18)
                .addGroup(jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneBefore)
                    .addComponent(txtPhoneBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneAfter)
                    .addComponent(txtPhoneAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPhoneUpd)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        lblDel.setText("정말 탈퇴하시겠습니까?");

        btnDelYes.setText("예");

        btnDelNo.setText("아니오");

        javax.swing.GroupLayout jDialogDelLayout = new javax.swing.GroupLayout(jDialogDel.getContentPane());
        jDialogDel.getContentPane().setLayout(jDialogDelLayout);
        jDialogDelLayout.setHorizontalGroup(
            jDialogDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDelLayout.createSequentialGroup()
                .addGroup(jDialogDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblDel))
                    .addGroup(jDialogDelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnDelYes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelNo)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jDialogDelLayout.setVerticalGroup(
            jDialogDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblDel)
                .addGap(26, 26, 26)
                .addGroup(jDialogDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelNo)
                    .addComponent(btnDelYes))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("레시피 공유 프로그램");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "제목", "작성자", "재료" }));

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnMyProfile.setText("내 정보");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneHeaderLayout = new javax.swing.GroupLayout(jPaneHeader);
        jPaneHeader.setLayout(jPaneHeaderLayout);
        jPaneHeaderLayout.setHorizontalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblLogo)
                    .addGap(46, 46, 46)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                    .addComponent(btnMyProfile)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLogout)
                    .addContainerGap()))
        );
        jPaneHeaderLayout.setVerticalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneHeaderLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLogo)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnMyProfile)
                        .addComponent(btnLogout)
                        .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelBookmarkLayout = new javax.swing.GroupLayout(jPanelBookmark);
        jPanelBookmark.setLayout(jPanelBookmarkLayout);
        jPanelBookmarkLayout.setHorizontalGroup(
            jPanelBookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanelBookmarkLayout.setVerticalGroup(
            jPanelBookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        BookmarkAndReview.addTab("북마크", jPanelBookmark);

        javax.swing.GroupLayout jPanelReviewLayout = new javax.swing.GroupLayout(jPanelReview);
        jPanelReview.setLayout(jPanelReviewLayout);
        jPanelReviewLayout.setHorizontalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanelReviewLayout.setVerticalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        BookmarkAndReview.addTab("내가 쓴 리뷰", jPanelReview);

        lblName.setText("닉네임 : ");

        lblPhone.setText("전화번호 : 010-0000-0000");

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookmarkAndReview, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(lblName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(BookmarkAndReview, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        new SubFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        new SearchResultFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        new MyProfileFrame().setVisible(true);
    }//GEN-LAST:event_btnMyProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BookmarkAndReview;
    private javax.swing.JButton btnDelNo;
    private javax.swing.JButton btnDelYes;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnNameUpd;
    private javax.swing.JButton btnPhoneUpd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JDialog jDialogDel;
    private javax.swing.JDialog jDialogName;
    private javax.swing.JDialog jDialogPhone;
    private javax.swing.JPanel jPaneHeader;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelBookmark;
    private javax.swing.JPanel jPanelReview;
    private javax.swing.JLabel lblDel;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameAfter;
    private javax.swing.JLabel lblNameBefore;
    private javax.swing.JLabel lblNameUpd;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneAfter;
    private javax.swing.JLabel lblPhoneBefore;
    private javax.swing.JLabel lblPhoneUpd;
    private javax.swing.JTextField txtNameAfter;
    private javax.swing.JTextField txtNameBefore;
    private javax.swing.JTextField txtPhoneAfter;
    private javax.swing.JTextField txtPhoneBefore;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
