
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author antaemin
 */
public class RecipeDetailFrame extends javax.swing.JFrame {
    private JSONObject recipeData; // 전달받은 데이터를 저장할 변수
    /**
     * Creates new form RecipeDetailFrame
     */
    public RecipeDetailFrame(JSONObject recipeData) {
        this.recipeData = recipeData;
        initComponents();
        displayRecipeDetails(); // 레시피 상세 정보를 화면에 표시
    }
    
    private void displayRecipeDetails() {
        if (recipeData != null) {
            try {
                // JSON 데이터에서 필요한 정보를 추출
                String title = recipeData.getString("title");
                String description = recipeData.getString("description");
                // 추가적으로 필요한 데이터가 있다면 계속해서 추출

                // UI 컴포넌트에 데이터 설정
                lblTitle.setText("제목: " + title);
                jTextAreaContent.setText(description);
                // 필요한 다른 컴포넌트에 데이터 추가
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "레시피 데이터를 불러오는 중 오류 발생!", "오류", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogReviewUpd = new javax.swing.JDialog();
        btnUpdReview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUpdateReview = new javax.swing.JTextArea();
        comboUpdGrade = new javax.swing.JComboBox<>();
        lblUpdGrade = new javax.swing.JLabel();
        lblUpdReview = new javax.swing.JLabel();
        jDialogReviewDel = new javax.swing.JDialog();
        lblDelReview = new javax.swing.JLabel();
        lblDelReviewConfirm = new javax.swing.JLabel();
        btnDelReviewYes = new javax.swing.JButton();
        btnDelReviewNo = new javax.swing.JButton();
        jDialogCommUpd = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaUpdComm = new javax.swing.JTextArea();
        btnDelComm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDialogCommDel = new javax.swing.JDialog();
        lblDelCommConfirm = new javax.swing.JLabel();
        btnDelCommYes = new javax.swing.JButton();
        btnDelCommNo = new javax.swing.JButton();
        lblDelComm = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanelImg = new javax.swing.JPanel();
        ReviewAndComment = new javax.swing.JTabbedPane();
        jPanelReview = new javax.swing.JPanel();
        lblReviewWriter1 = new javax.swing.JLabel();
        jScrollPaneReview1 = new javax.swing.JScrollPane();
        jTextAreaReview1 = new javax.swing.JTextArea();
        lblReviewCreate1 = new javax.swing.JLabel();
        lblReviewWriter2 = new javax.swing.JLabel();
        jScrollPaneReview2 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        lblReviewCreate2 = new javax.swing.JLabel();
        lblReviewWriter3 = new javax.swing.JLabel();
        jScrollPane1Review3 = new javax.swing.JScrollPane();
        jTextAreaReview3 = new javax.swing.JTextArea();
        lblReviewCreate3 = new javax.swing.JLabel();
        lblReviewCurrentPage = new javax.swing.JLabel();
        btnReviewNextPage = new javax.swing.JButton();
        btnReviewPrePage = new javax.swing.JButton();
        jScrollPaneReviewWrite = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        comboReviewGradeWrtie = new javax.swing.JComboBox<>();
        lblReviewGrade1 = new javax.swing.JLabel();
        lblReviewGrade2 = new javax.swing.JLabel();
        lblReviewGrade3 = new javax.swing.JLabel();
        lblReviewWriterWrite = new javax.swing.JLabel();
        btnReviewWrite = new javax.swing.JButton();
        lblReviewGradeWrite = new javax.swing.JLabel();
        btnReviewUpdForm1 = new javax.swing.JButton();
        btnReviewDelForm = new javax.swing.JButton();
        btnReviewUpdForm = new javax.swing.JButton();
        btnReviewDelForm2 = new javax.swing.JButton();
        btnReviewUpdForm3 = new javax.swing.JButton();
        btnReviewDelForm3 = new javax.swing.JButton();
        jPanelComment = new javax.swing.JPanel();
        lblCommWriter1 = new javax.swing.JLabel();
        jScrollPaneComm1 = new javax.swing.JScrollPane();
        jTextAreaComm1 = new javax.swing.JTextArea();
        lblCommCreate1 = new javax.swing.JLabel();
        lblCommWriter2 = new javax.swing.JLabel();
        jScrollPaneComm2 = new javax.swing.JScrollPane();
        jTextAreaComm2 = new javax.swing.JTextArea();
        lblCommCreate2 = new javax.swing.JLabel();
        lblCommWriter3 = new javax.swing.JLabel();
        jScrollPaneComm3 = new javax.swing.JScrollPane();
        jTextAreaComm3 = new javax.swing.JTextArea();
        lblCommCreate3 = new javax.swing.JLabel();
        lblCommCurrentPage = new javax.swing.JLabel();
        btnCommNextPage = new javax.swing.JButton();
        btnCommPrePage = new javax.swing.JButton();
        jScrollPaneCommWrite = new javax.swing.JScrollPane();
        jTextAreaCommWrite = new javax.swing.JTextArea();
        lblCommWriterWrite = new javax.swing.JLabel();
        btnCommWrite = new javax.swing.JButton();
        btnCommUpdForm1 = new javax.swing.JButton();
        btnCommDelForm1 = new javax.swing.JButton();
        btnCommUpdForm2 = new javax.swing.JButton();
        btnCommDelForm2 = new javax.swing.JButton();
        btnCommUpdForm3 = new javax.swing.JButton();
        btnCommDelForm3 = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        lblWriter = new javax.swing.JLabel();
        jScrollPaneOrder = new javax.swing.JScrollPane();
        jTextAreaOrder = new javax.swing.JTextArea();
        jScrollPaneNecess = new javax.swing.JScrollPane();
        jTextAreaNecess = new javax.swing.JTextArea();
        lblOrder = new javax.swing.JLabel();
        lblNecess = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        lblRefUrl = new javax.swing.JLabel();
        jScrollPaneContent = new javax.swing.JScrollPane();
        jTextAreaContent = new javax.swing.JTextArea();

        btnUpdReview.setText("수정하기");

        jTextAreaUpdateReview.setColumns(20);
        jTextAreaUpdateReview.setRows(5);
        jScrollPane1.setViewportView(jTextAreaUpdateReview);

        comboUpdGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));

        lblUpdGrade.setText("점수");

        lblUpdReview.setText("리뷰 수정하기");

        javax.swing.GroupLayout jDialogReviewUpdLayout = new javax.swing.GroupLayout(jDialogReviewUpd.getContentPane());
        jDialogReviewUpd.getContentPane().setLayout(jDialogReviewUpdLayout);
        jDialogReviewUpdLayout.setHorizontalGroup(
            jDialogReviewUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogReviewUpdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogReviewUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogReviewUpdLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdReview))
                    .addGroup(jDialogReviewUpdLayout.createSequentialGroup()
                        .addComponent(lblUpdGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboUpdGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogReviewUpdLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lblUpdReview)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jDialogReviewUpdLayout.setVerticalGroup(
            jDialogReviewUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogReviewUpdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdReview)
                .addGap(18, 18, 18)
                .addGroup(jDialogReviewUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdGrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdReview)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblDelReview.setText("리뷰 삭제하기");

        lblDelReviewConfirm.setText("삭제하시겠습니까?");

        btnDelReviewYes.setText("예");

        btnDelReviewNo.setText("아니오");

        javax.swing.GroupLayout jDialogReviewDelLayout = new javax.swing.GroupLayout(jDialogReviewDel.getContentPane());
        jDialogReviewDel.getContentPane().setLayout(jDialogReviewDelLayout);
        jDialogReviewDelLayout.setHorizontalGroup(
            jDialogReviewDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogReviewDelLayout.createSequentialGroup()
                .addGroup(jDialogReviewDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogReviewDelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblDelReview))
                    .addGroup(jDialogReviewDelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblDelReviewConfirm))
                    .addGroup(jDialogReviewDelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnDelReviewYes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnDelReviewNo)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jDialogReviewDelLayout.setVerticalGroup(
            jDialogReviewDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogReviewDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDelReview)
                .addGap(51, 51, 51)
                .addComponent(lblDelReviewConfirm)
                .addGap(54, 54, 54)
                .addGroup(jDialogReviewDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelReviewNo)
                    .addComponent(btnDelReviewYes))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTextAreaUpdComm.setColumns(20);
        jTextAreaUpdComm.setRows(5);
        jScrollPane2.setViewportView(jTextAreaUpdComm);

        btnDelComm.setText("수정하기");

        jLabel1.setText("댓글 수정하기");

        javax.swing.GroupLayout jDialogCommUpdLayout = new javax.swing.GroupLayout(jDialogCommUpd.getContentPane());
        jDialogCommUpd.getContentPane().setLayout(jDialogCommUpdLayout);
        jDialogCommUpdLayout.setHorizontalGroup(
            jDialogCommUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCommUpdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogCommUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCommUpdLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelComm)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCommUpdLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
        );
        jDialogCommUpdLayout.setVerticalGroup(
            jDialogCommUpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCommUpdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnDelComm)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        lblDelCommConfirm.setText("삭제하시겠습니까?");

        btnDelCommYes.setText("예");

        btnDelCommNo.setText("아니오");

        lblDelComm.setText("댓글 삭제하기");

        javax.swing.GroupLayout jDialogCommDelLayout = new javax.swing.GroupLayout(jDialogCommDel.getContentPane());
        jDialogCommDel.getContentPane().setLayout(jDialogCommDelLayout);
        jDialogCommDelLayout.setHorizontalGroup(
            jDialogCommDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCommDelLayout.createSequentialGroup()
                .addGroup(jDialogCommDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCommDelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblDelComm))
                    .addGroup(jDialogCommDelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblDelCommConfirm))
                    .addGroup(jDialogCommDelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnDelCommYes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnDelCommNo)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jDialogCommDelLayout.setVerticalGroup(
            jDialogCommDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCommDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDelComm)
                .addGap(51, 51, 51)
                .addComponent(lblDelCommConfirm)
                .addGap(54, 54, 54)
                .addGroup(jDialogCommDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelCommNo)
                    .addComponent(btnDelCommYes))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("레시피 공유 프로그램");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "제목", "작성자", "재료" }));

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnMyProfile.setText("내 정보");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblLogo)
                    .addGap(46, 46, 46)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                    .addComponent(btnMyProfile)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLogout)
                    .addContainerGap()))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLogo)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnMyProfile)
                        .addComponent(btnLogout)
                        .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblTitle.setText("제목");

        jPanelImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelImgLayout = new javax.swing.GroupLayout(jPanelImg);
        jPanelImg.setLayout(jPanelImgLayout);
        jPanelImgLayout.setHorizontalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jPanelImgLayout.setVerticalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        lblReviewWriter1.setText("작성자 : 홍길동");

        jTextAreaReview1.setColumns(20);
        jTextAreaReview1.setRows(5);
        jScrollPaneReview1.setViewportView(jTextAreaReview1);

        lblReviewCreate1.setText("2025.01.01");

        lblReviewWriter2.setText("작성자 : 홍길동");

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jScrollPaneReview2.setViewportView(jTextArea13);

        lblReviewCreate2.setText("2025.01.01");

        lblReviewWriter3.setText("작성자 : 홍길동");

        jTextAreaReview3.setColumns(20);
        jTextAreaReview3.setRows(5);
        jScrollPane1Review3.setViewportView(jTextAreaReview3);

        lblReviewCreate3.setText("2025.01.01");

        lblReviewCurrentPage.setText("1");

        btnReviewNextPage.setText(">");

        btnReviewPrePage.setText("<");
        btnReviewPrePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewPrePageActionPerformed(evt);
            }
        });

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jScrollPaneReviewWrite.setViewportView(jTextArea15);

        comboReviewGradeWrtie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));

        lblReviewGrade1.setText("점수 : 5");

        lblReviewGrade2.setText("점수 : 5");

        lblReviewGrade3.setText("점수 : 5");

        lblReviewWriterWrite.setText("작성자 : 홍길동");

        btnReviewWrite.setText("작성하기");

        lblReviewGradeWrite.setText("점수 :");

        btnReviewUpdForm1.setText("수정");
        btnReviewUpdForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewUpdForm1ActionPerformed(evt);
            }
        });

        btnReviewDelForm.setText("삭제");
        btnReviewDelForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewDelFormActionPerformed(evt);
            }
        });

        btnReviewUpdForm.setText("수정");
        btnReviewUpdForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewUpdFormActionPerformed(evt);
            }
        });

        btnReviewDelForm2.setText("삭제");
        btnReviewDelForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewDelForm2ActionPerformed(evt);
            }
        });

        btnReviewUpdForm3.setText("수정");
        btnReviewUpdForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewUpdForm3ActionPerformed(evt);
            }
        });

        btnReviewDelForm3.setText("삭제");
        btnReviewDelForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewDelForm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReviewLayout = new javax.swing.GroupLayout(jPanelReview);
        jPanelReview.setLayout(jPanelReviewLayout);
        jPanelReviewLayout.setHorizontalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addComponent(lblReviewWriterWrite)
                                .addGap(18, 18, 18)
                                .addComponent(lblReviewGradeWrite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboReviewGradeWrtie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addComponent(lblReviewWriter1)
                                .addGap(18, 18, 18)
                                .addComponent(lblReviewGrade1))
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addComponent(lblReviewWriter2)
                                .addGap(18, 18, 18)
                                .addComponent(lblReviewGrade2))
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addComponent(lblReviewWriter3)
                                .addGap(18, 18, 18)
                                .addComponent(lblReviewGrade3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReviewCreate1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblReviewCreate2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblReviewCreate3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPaneReviewWrite)
                    .addComponent(jScrollPane1Review3)
                    .addComponent(jScrollPaneReview2)
                    .addComponent(jScrollPaneReview1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReviewWrite, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                                .addComponent(btnReviewUpdForm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReviewDelForm))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                                .addComponent(btnReviewUpdForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReviewDelForm2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                                .addComponent(btnReviewUpdForm3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReviewDelForm3)))))
                .addContainerGap())
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(btnReviewPrePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReviewCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReviewNextPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReviewLayout.setVerticalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter1)
                    .addComponent(lblReviewCreate1)
                    .addComponent(lblReviewGrade1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReviewUpdForm1)
                    .addComponent(btnReviewDelForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter2)
                    .addComponent(lblReviewCreate2)
                    .addComponent(lblReviewGrade2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReview2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReviewUpdForm)
                    .addComponent(btnReviewDelForm2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter3)
                    .addComponent(lblReviewCreate3)
                    .addComponent(lblReviewGrade3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1Review3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReviewUpdForm3)
                    .addComponent(btnReviewDelForm3))
                .addGap(1, 1, 1)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReviewGradeWrtie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReviewWriterWrite)
                    .addComponent(lblReviewGradeWrite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReviewWrite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReviewWrite)
                .addGap(41, 41, 41)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewCurrentPage)
                    .addComponent(btnReviewNextPage)
                    .addComponent(btnReviewPrePage))
                .addContainerGap())
        );

        ReviewAndComment.addTab("리뷰", jPanelReview);

        lblCommWriter1.setText("작성자 : 홍길동");

        jTextAreaComm1.setColumns(20);
        jTextAreaComm1.setRows(5);
        jScrollPaneComm1.setViewportView(jTextAreaComm1);

        lblCommCreate1.setText("2025.01.01");

        lblCommWriter2.setText("작성자 : 홍길동");

        jTextAreaComm2.setColumns(20);
        jTextAreaComm2.setRows(5);
        jScrollPaneComm2.setViewportView(jTextAreaComm2);

        lblCommCreate2.setText("2025.01.01");

        lblCommWriter3.setText("작성자 : 홍길동");

        jTextAreaComm3.setColumns(20);
        jTextAreaComm3.setRows(5);
        jScrollPaneComm3.setViewportView(jTextAreaComm3);

        lblCommCreate3.setText("2025.01.01");

        lblCommCurrentPage.setText("1");

        btnCommNextPage.setText(">");

        btnCommPrePage.setText("<");
        btnCommPrePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommPrePageActionPerformed(evt);
            }
        });

        jTextAreaCommWrite.setColumns(20);
        jTextAreaCommWrite.setRows(5);
        jScrollPaneCommWrite.setViewportView(jTextAreaCommWrite);

        lblCommWriterWrite.setText("작성자 : 홍길동");

        btnCommWrite.setText("작성하기");

        btnCommUpdForm1.setText("수정");
        btnCommUpdForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommUpdForm1ActionPerformed(evt);
            }
        });

        btnCommDelForm1.setText("삭제");
        btnCommDelForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommDelForm1ActionPerformed(evt);
            }
        });

        btnCommUpdForm2.setText("수정");
        btnCommUpdForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommUpdForm2ActionPerformed(evt);
            }
        });

        btnCommDelForm2.setText("삭제");
        btnCommDelForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommDelForm2ActionPerformed(evt);
            }
        });

        btnCommUpdForm3.setText("수정");
        btnCommUpdForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommUpdForm3ActionPerformed(evt);
            }
        });

        btnCommDelForm3.setText("삭제");
        btnCommDelForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommDelForm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCommentLayout = new javax.swing.GroupLayout(jPanelComment);
        jPanelComment.setLayout(jPanelCommentLayout);
        jPanelCommentLayout.setHorizontalGroup(
            jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneComm1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneComm2)
                    .addGroup(jPanelCommentLayout.createSequentialGroup()
                        .addComponent(lblCommWriter2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommCreate2))
                    .addComponent(jScrollPaneComm3)
                    .addGroup(jPanelCommentLayout.createSequentialGroup()
                        .addComponent(lblCommWriter3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommCreate3))
                    .addGroup(jPanelCommentLayout.createSequentialGroup()
                        .addComponent(lblCommWriter1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCommCreate1))
                    .addGroup(jPanelCommentLayout.createSequentialGroup()
                        .addComponent(lblCommWriterWrite)
                        .addGap(642, 642, 642))
                    .addComponent(jScrollPaneCommWrite)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCommentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCommentLayout.createSequentialGroup()
                                .addComponent(btnCommUpdForm3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCommDelForm3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCommentLayout.createSequentialGroup()
                                .addComponent(btnCommUpdForm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCommDelForm1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCommentLayout.createSequentialGroup()
                                .addComponent(btnCommUpdForm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCommDelForm2))
                            .addComponent(btnCommWrite, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnCommPrePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCommCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCommNextPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCommentLayout.setVerticalGroup(
            jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter1)
                    .addComponent(lblCommCreate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommUpdForm1)
                    .addComponent(btnCommDelForm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter2)
                    .addComponent(lblCommCreate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommUpdForm2)
                    .addComponent(btnCommDelForm2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter3)
                    .addComponent(lblCommCreate3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommUpdForm3)
                    .addComponent(btnCommDelForm3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCommWriterWrite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCommWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCommWrite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommCurrentPage)
                    .addComponent(btnCommNextPage)
                    .addComponent(btnCommPrePage))
                .addContainerGap())
        );

        ReviewAndComment.addTab("댓글", jPanelComment);

        lblCreate.setText("작성일자 : 2025.01.01");

        lblWriter.setText("작성자 : 홍길동");

        jTextAreaOrder.setColumns(20);
        jTextAreaOrder.setRows(5);
        jScrollPaneOrder.setViewportView(jTextAreaOrder);

        jTextAreaNecess.setColumns(20);
        jTextAreaNecess.setRows(5);
        jScrollPaneNecess.setViewportView(jTextAreaNecess);

        lblOrder.setText("조리 순서");

        lblNecess.setText("필요한 재료");

        lblSite.setText("참고 사이트");

        lblRefUrl.setText("uri : www.youtube.com");

        jTextAreaContent.setColumns(20);
        jTextAreaContent.setRows(5);
        jTextAreaContent.setText("내용");
        jScrollPaneContent.setViewportView(jTextAreaContent);

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReviewAndComment)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrder)
                            .addComponent(lblNecess)
                            .addComponent(lblSite)
                            .addComponent(lblRefUrl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                                .addComponent(jPanelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(lblTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblWriter)
                                            .addComponent(lblCreate)))
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneContent))))
                            .addComponent(jScrollPaneNecess)
                            .addComponent(jScrollPaneOrder))
                        .addContainerGap())))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(lblCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWriter)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneContent, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lblNecess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneNecess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRefUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReviewAndComment))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        new SubFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        new SearchResultFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReviewPrePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewPrePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReviewPrePageActionPerformed

    private void btnCommPrePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommPrePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommPrePageActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        new MyProfileFrame().setVisible(true);
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void btnReviewUpdForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewUpdForm1ActionPerformed
        // TODO add your handling code here:
        jDialogReviewUpd.setSize(400, 350);
        jDialogReviewUpd.setVisible(true);
    }//GEN-LAST:event_btnReviewUpdForm1ActionPerformed

    private void btnReviewDelFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewDelFormActionPerformed
        // TODO add your handling code here:
        jDialogReviewDel.setSize(400, 350);
        jDialogReviewDel.setVisible(true);
    }//GEN-LAST:event_btnReviewDelFormActionPerformed

    private void btnReviewUpdFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewUpdFormActionPerformed
        // TODO add your handling code here:
        jDialogReviewUpd.setSize(400, 350);
        jDialogReviewUpd.setVisible(true);
    }//GEN-LAST:event_btnReviewUpdFormActionPerformed

    private void btnReviewDelForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewDelForm2ActionPerformed
        // TODO add your handling code here:
        jDialogReviewDel.setSize(400, 350);
        jDialogReviewDel.setVisible(true);
    }//GEN-LAST:event_btnReviewDelForm2ActionPerformed

    private void btnReviewUpdForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewUpdForm3ActionPerformed
        // TODO add your handling code here:
        jDialogReviewUpd.setSize(400, 350);
        jDialogReviewUpd.setVisible(true);
    }//GEN-LAST:event_btnReviewUpdForm3ActionPerformed

    private void btnReviewDelForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewDelForm3ActionPerformed
        // TODO add your handling code here:
        jDialogReviewDel.setSize(400, 350);
        jDialogReviewDel.setVisible(true);
    }//GEN-LAST:event_btnReviewDelForm3ActionPerformed

    private void btnCommUpdForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommUpdForm1ActionPerformed
        // TODO add your handling code here:
        jDialogCommUpd.setSize(400, 350);
        jDialogCommUpd.setVisible(true);
    }//GEN-LAST:event_btnCommUpdForm1ActionPerformed

    private void btnCommDelForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommDelForm1ActionPerformed
        // TODO add your handling code here:
        jDialogCommDel.setSize(400, 350);
        jDialogCommDel.setVisible(true);
    }//GEN-LAST:event_btnCommDelForm1ActionPerformed

    private void btnCommUpdForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommUpdForm2ActionPerformed
        // TODO add your handling code here:
        jDialogCommUpd.setSize(400, 350);
        jDialogCommUpd.setVisible(true);
    }//GEN-LAST:event_btnCommUpdForm2ActionPerformed

    private void btnCommDelForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommDelForm2ActionPerformed
        // TODO add your handling code here:
        jDialogCommDel.setSize(400, 350);
        jDialogCommDel.setVisible(true);
    }//GEN-LAST:event_btnCommDelForm2ActionPerformed

    private void btnCommUpdForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommUpdForm3ActionPerformed
        // TODO add your handling code here:
        jDialogCommUpd.setSize(400, 350);
        jDialogCommUpd.setVisible(true);
    }//GEN-LAST:event_btnCommUpdForm3ActionPerformed

    private void btnCommDelForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommDelForm3ActionPerformed
        // TODO add your handling code here:
        jDialogCommDel.setSize(400, 350);
        jDialogCommDel.setVisible(true);
    }//GEN-LAST:event_btnCommDelForm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new RecipeDetailFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ReviewAndComment;
    private javax.swing.JButton btnCommDelForm1;
    private javax.swing.JButton btnCommDelForm2;
    private javax.swing.JButton btnCommDelForm3;
    private javax.swing.JButton btnCommNextPage;
    private javax.swing.JButton btnCommPrePage;
    private javax.swing.JButton btnCommUpdForm1;
    private javax.swing.JButton btnCommUpdForm2;
    private javax.swing.JButton btnCommUpdForm3;
    private javax.swing.JButton btnCommWrite;
    private javax.swing.JButton btnDelComm;
    private javax.swing.JButton btnDelCommNo;
    private javax.swing.JButton btnDelCommYes;
    private javax.swing.JButton btnDelReviewNo;
    private javax.swing.JButton btnDelReviewYes;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnReviewDelForm;
    private javax.swing.JButton btnReviewDelForm2;
    private javax.swing.JButton btnReviewDelForm3;
    private javax.swing.JButton btnReviewNextPage;
    private javax.swing.JButton btnReviewPrePage;
    private javax.swing.JButton btnReviewUpdForm;
    private javax.swing.JButton btnReviewUpdForm1;
    private javax.swing.JButton btnReviewUpdForm3;
    private javax.swing.JButton btnReviewWrite;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdReview;
    private javax.swing.JComboBox<String> comboReviewGradeWrtie;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JComboBox<String> comboUpdGrade;
    private javax.swing.JDialog jDialogCommDel;
    private javax.swing.JDialog jDialogCommUpd;
    private javax.swing.JDialog jDialogReviewDel;
    private javax.swing.JDialog jDialogReviewUpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelComment;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelImg;
    private javax.swing.JPanel jPanelReview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane1Review3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneComm1;
    private javax.swing.JScrollPane jScrollPaneComm2;
    private javax.swing.JScrollPane jScrollPaneComm3;
    private javax.swing.JScrollPane jScrollPaneCommWrite;
    private javax.swing.JScrollPane jScrollPaneContent;
    private javax.swing.JScrollPane jScrollPaneNecess;
    private javax.swing.JScrollPane jScrollPaneOrder;
    private javax.swing.JScrollPane jScrollPaneReview1;
    private javax.swing.JScrollPane jScrollPaneReview2;
    private javax.swing.JScrollPane jScrollPaneReviewWrite;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextAreaComm1;
    private javax.swing.JTextArea jTextAreaComm2;
    private javax.swing.JTextArea jTextAreaComm3;
    private javax.swing.JTextArea jTextAreaCommWrite;
    private javax.swing.JTextArea jTextAreaContent;
    private javax.swing.JTextArea jTextAreaNecess;
    private javax.swing.JTextArea jTextAreaOrder;
    private javax.swing.JTextArea jTextAreaReview1;
    private javax.swing.JTextArea jTextAreaReview3;
    private javax.swing.JTextArea jTextAreaUpdComm;
    private javax.swing.JTextArea jTextAreaUpdateReview;
    private javax.swing.JLabel lblCommCreate1;
    private javax.swing.JLabel lblCommCreate2;
    private javax.swing.JLabel lblCommCreate3;
    private javax.swing.JLabel lblCommCurrentPage;
    private javax.swing.JLabel lblCommWriter1;
    private javax.swing.JLabel lblCommWriter2;
    private javax.swing.JLabel lblCommWriter3;
    private javax.swing.JLabel lblCommWriterWrite;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDelComm;
    private javax.swing.JLabel lblDelCommConfirm;
    private javax.swing.JLabel lblDelReview;
    private javax.swing.JLabel lblDelReviewConfirm;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNecess;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblRefUrl;
    private javax.swing.JLabel lblReviewCreate1;
    private javax.swing.JLabel lblReviewCreate2;
    private javax.swing.JLabel lblReviewCreate3;
    private javax.swing.JLabel lblReviewCurrentPage;
    private javax.swing.JLabel lblReviewGrade1;
    private javax.swing.JLabel lblReviewGrade2;
    private javax.swing.JLabel lblReviewGrade3;
    private javax.swing.JLabel lblReviewGradeWrite;
    private javax.swing.JLabel lblReviewWriter1;
    private javax.swing.JLabel lblReviewWriter2;
    private javax.swing.JLabel lblReviewWriter3;
    private javax.swing.JLabel lblReviewWriterWrite;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdGrade;
    private javax.swing.JLabel lblUpdReview;
    private javax.swing.JLabel lblWriter;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
