/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author antaemin
 */
public class RecipeDetailFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecipeDetailFrame
     */
    public RecipeDetailFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanelImg = new javax.swing.JPanel();
        ReviewAndComment = new javax.swing.JTabbedPane();
        jPanelReview = new javax.swing.JPanel();
        lblReviewWriter1 = new javax.swing.JLabel();
        jScrollPaneReview1 = new javax.swing.JScrollPane();
        jTextAreaReview1 = new javax.swing.JTextArea();
        lblReviewCreate1 = new javax.swing.JLabel();
        lblReviewWriter2 = new javax.swing.JLabel();
        jScrollPaneReview2 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        lblReviewCreate2 = new javax.swing.JLabel();
        lblReviewWriter3 = new javax.swing.JLabel();
        jScrollPane1Review3 = new javax.swing.JScrollPane();
        jTextAreaReview3 = new javax.swing.JTextArea();
        lblReviewCreate3 = new javax.swing.JLabel();
        lblReviewCurrentPage = new javax.swing.JLabel();
        btnReviewNextPage = new javax.swing.JButton();
        btnReviewPrePage = new javax.swing.JButton();
        jScrollPaneReviewWrite = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        comboReviewGradeWrtie = new javax.swing.JComboBox<>();
        lblReviewGrade1 = new javax.swing.JLabel();
        lblReviewGrade2 = new javax.swing.JLabel();
        lblReviewGrade3 = new javax.swing.JLabel();
        lblReviewWriterWrite = new javax.swing.JLabel();
        btnReviewWrite = new javax.swing.JButton();
        lblReviewGradeWrite = new javax.swing.JLabel();
        jPanelComment = new javax.swing.JPanel();
        lblCommWriter1 = new javax.swing.JLabel();
        jScrollPaneComm1 = new javax.swing.JScrollPane();
        jTextAreaComm1 = new javax.swing.JTextArea();
        lblCommCreate1 = new javax.swing.JLabel();
        lblCommWriter2 = new javax.swing.JLabel();
        jScrollPaneComm2 = new javax.swing.JScrollPane();
        jTextAreaComm2 = new javax.swing.JTextArea();
        lblCommCreate2 = new javax.swing.JLabel();
        lblCommWriter3 = new javax.swing.JLabel();
        jScrollPaneComm3 = new javax.swing.JScrollPane();
        jTextAreaComm3 = new javax.swing.JTextArea();
        lblCommCreate3 = new javax.swing.JLabel();
        lblCommCurrentPage = new javax.swing.JLabel();
        btnCommNextPage = new javax.swing.JButton();
        btnCommPrePage = new javax.swing.JButton();
        jScrollPaneCommWrite = new javax.swing.JScrollPane();
        jTextAreaCommWrite = new javax.swing.JTextArea();
        lblCommWriterWrite = new javax.swing.JLabel();
        btnCommWrite = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        lblWriter = new javax.swing.JLabel();
        jScrollPaneOrder = new javax.swing.JScrollPane();
        jTextAreaOrder = new javax.swing.JTextArea();
        jScrollPaneNecess = new javax.swing.JScrollPane();
        jTextAreaNecess = new javax.swing.JTextArea();
        lblOrder = new javax.swing.JLabel();
        lblNecess = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        lblRefUrl = new javax.swing.JLabel();
        jScrollPaneContent = new javax.swing.JScrollPane();
        jTextAreaContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("레시피 공유 프로그램");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "제목", "작성자", "재료" }));

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnMyProfile.setText("내 정보");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblLogo)
                    .addGap(46, 46, 46)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                    .addComponent(btnMyProfile)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLogout)
                    .addContainerGap()))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLogo)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnMyProfile)
                        .addComponent(btnLogout)
                        .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblTitle.setText("제목");

        jPanelImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelImgLayout = new javax.swing.GroupLayout(jPanelImg);
        jPanelImg.setLayout(jPanelImgLayout);
        jPanelImgLayout.setHorizontalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jPanelImgLayout.setVerticalGroup(
            jPanelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        lblReviewWriter1.setText("작성자 : 홍길동");

        jTextAreaReview1.setColumns(20);
        jTextAreaReview1.setRows(5);
        jScrollPaneReview1.setViewportView(jTextAreaReview1);

        lblReviewCreate1.setText("2025.01.01");

        lblReviewWriter2.setText("작성자 : 홍길동");

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jScrollPaneReview2.setViewportView(jTextArea13);

        lblReviewCreate2.setText("2025.01.01");

        lblReviewWriter3.setText("작성자 : 홍길동");

        jTextAreaReview3.setColumns(20);
        jTextAreaReview3.setRows(5);
        jScrollPane1Review3.setViewportView(jTextAreaReview3);

        lblReviewCreate3.setText("2025.01.01");

        lblReviewCurrentPage.setText("1");

        btnReviewNextPage.setText(">");

        btnReviewPrePage.setText("<");
        btnReviewPrePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewPrePageActionPerformed(evt);
            }
        });

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jScrollPaneReviewWrite.setViewportView(jTextArea15);

        comboReviewGradeWrtie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));

        lblReviewGrade1.setText("점수 : 5");

        lblReviewGrade2.setText("점수 : 5");

        lblReviewGrade3.setText("점수 : 5");

        lblReviewWriterWrite.setText("작성자 : 홍길동");

        btnReviewWrite.setText("작성하기");

        lblReviewGradeWrite.setText("점수 :");

        javax.swing.GroupLayout jPanelReviewLayout = new javax.swing.GroupLayout(jPanelReview);
        jPanelReview.setLayout(jPanelReviewLayout);
        jPanelReviewLayout.setHorizontalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addComponent(lblReviewWriterWrite)
                                .addGap(18, 18, 18)
                                .addComponent(lblReviewGradeWrite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboReviewGradeWrtie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE))
                            .addGroup(jPanelReviewLayout.createSequentialGroup()
                                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                                        .addComponent(lblReviewWriter1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblReviewGrade1))
                                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                                        .addComponent(lblReviewWriter2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblReviewGrade2))
                                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                                        .addComponent(lblReviewWriter3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblReviewGrade3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReviewCreate1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReviewCreate2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblReviewCreate3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                        .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneReviewWrite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1Review3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneReview2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneReview1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReviewWrite)
                .addContainerGap())
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(btnReviewPrePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReviewCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReviewNextPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReviewLayout.setVerticalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter1)
                    .addComponent(lblReviewCreate1)
                    .addComponent(lblReviewGrade1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter2)
                    .addComponent(lblReviewCreate2)
                    .addComponent(lblReviewGrade2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReview2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewWriter3)
                    .addComponent(lblReviewCreate3)
                    .addComponent(lblReviewGrade3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1Review3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReviewGradeWrtie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReviewWriterWrite)
                    .addComponent(lblReviewGradeWrite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReviewWrite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReviewWrite)
                .addGap(18, 18, 18)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReviewCurrentPage)
                    .addComponent(btnReviewNextPage)
                    .addComponent(btnReviewPrePage))
                .addContainerGap())
        );

        ReviewAndComment.addTab("리뷰", jPanelReview);

        lblCommWriter1.setText("작성자 : 홍길동");

        jTextAreaComm1.setColumns(20);
        jTextAreaComm1.setRows(5);
        jScrollPaneComm1.setViewportView(jTextAreaComm1);

        lblCommCreate1.setText("2025.01.01");

        lblCommWriter2.setText("작성자 : 홍길동");

        jTextAreaComm2.setColumns(20);
        jTextAreaComm2.setRows(5);
        jScrollPaneComm2.setViewportView(jTextAreaComm2);

        lblCommCreate2.setText("2025.01.01");

        lblCommWriter3.setText("작성자 : 홍길동");

        jTextAreaComm3.setColumns(20);
        jTextAreaComm3.setRows(5);
        jScrollPaneComm3.setViewportView(jTextAreaComm3);

        lblCommCreate3.setText("2025.01.01");

        lblCommCurrentPage.setText("1");

        btnCommNextPage.setText(">");

        btnCommPrePage.setText("<");
        btnCommPrePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommPrePageActionPerformed(evt);
            }
        });

        jTextAreaCommWrite.setColumns(20);
        jTextAreaCommWrite.setRows(5);
        jScrollPaneCommWrite.setViewportView(jTextAreaCommWrite);

        lblCommWriterWrite.setText("작성자 : 홍길동");

        btnCommWrite.setText("작성하기");

        javax.swing.GroupLayout jPanelCommentLayout = new javax.swing.GroupLayout(jPanelComment);
        jPanelComment.setLayout(jPanelCommentLayout);
        jPanelCommentLayout.setHorizontalGroup(
            jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCommentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneComm2, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                            .addGroup(jPanelCommentLayout.createSequentialGroup()
                                .addComponent(lblCommWriter2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCommCreate2))
                            .addComponent(jScrollPaneComm3)
                            .addGroup(jPanelCommentLayout.createSequentialGroup()
                                .addComponent(lblCommWriter3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCommCreate3))
                            .addComponent(jScrollPaneCommWrite)
                            .addGroup(jPanelCommentLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCommWrite))
                            .addGroup(jPanelCommentLayout.createSequentialGroup()
                                .addComponent(lblCommWriterWrite)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCommentLayout.createSequentialGroup()
                                .addComponent(lblCommWriter1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCommCreate1))))
                    .addComponent(jScrollPaneComm1))
                .addContainerGap())
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(btnCommPrePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCommCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCommNextPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCommentLayout.setVerticalGroup(
            jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter1)
                    .addComponent(lblCommCreate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter2)
                    .addComponent(lblCommCreate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommWriter3)
                    .addComponent(lblCommCreate3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComm3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCommWriterWrite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCommWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommWrite)
                .addGap(18, 18, 18)
                .addGroup(jPanelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommCurrentPage)
                    .addComponent(btnCommNextPage)
                    .addComponent(btnCommPrePage))
                .addContainerGap())
        );

        ReviewAndComment.addTab("댓글", jPanelComment);

        lblCreate.setText("작성일자 : 2025.01.01");

        lblWriter.setText("작성자 : 홍길동");

        jTextAreaOrder.setColumns(20);
        jTextAreaOrder.setRows(5);
        jScrollPaneOrder.setViewportView(jTextAreaOrder);

        jTextAreaNecess.setColumns(20);
        jTextAreaNecess.setRows(5);
        jScrollPaneNecess.setViewportView(jTextAreaNecess);

        lblOrder.setText("조리 순서");

        lblNecess.setText("필요한 재료");

        lblSite.setText("참고 사이트");

        lblRefUrl.setText("uri : www.youtube.com");

        jTextAreaContent.setColumns(20);
        jTextAreaContent.setRows(5);
        jTextAreaContent.setText("내용");
        jScrollPaneContent.setViewportView(jTextAreaContent);

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReviewAndComment)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrder)
                            .addComponent(lblNecess)
                            .addComponent(lblSite)
                            .addComponent(lblRefUrl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                                .addComponent(jPanelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(lblTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblWriter)
                                            .addComponent(lblCreate)))
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneContent))))
                            .addComponent(jScrollPaneNecess)
                            .addComponent(jScrollPaneOrder))
                        .addContainerGap())))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(lblCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWriter)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneContent, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblNecess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneNecess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRefUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReviewAndComment, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        new SubFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        new SearchResultFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReviewPrePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewPrePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReviewPrePageActionPerformed

    private void btnCommPrePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommPrePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommPrePageActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        new MyProfileFrame().setVisible(true);
    }//GEN-LAST:event_btnMyProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeDetailFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ReviewAndComment;
    private javax.swing.JButton btnCommNextPage;
    private javax.swing.JButton btnCommPrePage;
    private javax.swing.JButton btnCommWrite;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnReviewNextPage;
    private javax.swing.JButton btnReviewPrePage;
    private javax.swing.JButton btnReviewWrite;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboReviewGradeWrtie;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelComment;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelImg;
    private javax.swing.JPanel jPanelReview;
    private javax.swing.JScrollPane jScrollPane1Review3;
    private javax.swing.JScrollPane jScrollPaneComm1;
    private javax.swing.JScrollPane jScrollPaneComm2;
    private javax.swing.JScrollPane jScrollPaneComm3;
    private javax.swing.JScrollPane jScrollPaneCommWrite;
    private javax.swing.JScrollPane jScrollPaneContent;
    private javax.swing.JScrollPane jScrollPaneNecess;
    private javax.swing.JScrollPane jScrollPaneOrder;
    private javax.swing.JScrollPane jScrollPaneReview1;
    private javax.swing.JScrollPane jScrollPaneReview2;
    private javax.swing.JScrollPane jScrollPaneReviewWrite;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextAreaComm1;
    private javax.swing.JTextArea jTextAreaComm2;
    private javax.swing.JTextArea jTextAreaComm3;
    private javax.swing.JTextArea jTextAreaCommWrite;
    private javax.swing.JTextArea jTextAreaContent;
    private javax.swing.JTextArea jTextAreaNecess;
    private javax.swing.JTextArea jTextAreaOrder;
    private javax.swing.JTextArea jTextAreaReview1;
    private javax.swing.JTextArea jTextAreaReview3;
    private javax.swing.JLabel lblCommCreate1;
    private javax.swing.JLabel lblCommCreate2;
    private javax.swing.JLabel lblCommCreate3;
    private javax.swing.JLabel lblCommCurrentPage;
    private javax.swing.JLabel lblCommWriter1;
    private javax.swing.JLabel lblCommWriter2;
    private javax.swing.JLabel lblCommWriter3;
    private javax.swing.JLabel lblCommWriterWrite;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNecess;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblRefUrl;
    private javax.swing.JLabel lblReviewCreate1;
    private javax.swing.JLabel lblReviewCreate2;
    private javax.swing.JLabel lblReviewCreate3;
    private javax.swing.JLabel lblReviewCurrentPage;
    private javax.swing.JLabel lblReviewGrade1;
    private javax.swing.JLabel lblReviewGrade2;
    private javax.swing.JLabel lblReviewGrade3;
    private javax.swing.JLabel lblReviewGradeWrite;
    private javax.swing.JLabel lblReviewWriter1;
    private javax.swing.JLabel lblReviewWriter2;
    private javax.swing.JLabel lblReviewWriter3;
    private javax.swing.JLabel lblReviewWriterWrite;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWriter;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
