
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.json.JSONArray;
import org.json.JSONObject;
import util.TokenUtil;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Study
 */
public class SearchResultFrame extends javax.swing.JFrame {
    private int currentPage = 1; // 현재 페이지
    private final int itemsPerPage = 3; // 한 페이지에 표시할 항목 수
    private JSONArray results; // 검색 결과 저장

    /**
     * Creates new form SearchResultFrame
     */
    // 결과를 페이징 처리하여 표시하는 메서드
    public SearchResultFrame() {
        initComponents();
    }
    
    
    public void displayResults(JSONArray fullResults) {
        this.results = fullResults; // 전체 결과를 저장
        updatePage(); // 현재 페이지를 업데이트
    }

    // 현재 페이지에 해당하는 항목만 표시
    private void updatePage() {
        //컴포넌트 보이게 초기화
        jPanelResultList1.setVisible(true);
        jPanelResultList2.setVisible(true);
        jPanelResultList3.setVisible(true);
        
        int start = (currentPage - 1) * itemsPerPage;
        int end = Math.min(start + itemsPerPage, results.length());
        
        if (end == 0) {
            jPanelResultList1.setVisible(false);
            jPanelResultList2.setVisible(false);
            jPanelResultList3.setVisible(false);
        }
        
        for (int i = 0; i < end; i++) {
            if (i % 3 == 0) {
                lblResultTitle1.setText("제목: " + results.getJSONObject(i).getString("title"));
                lblResultWriter1.setText("작성자: " + results.getJSONObject(i).getString("name"));
                lblVisit1.setText("조회수: " + results.getJSONObject(i).getInt("visited"));
            } else if (i % 3 == 1) {
                lblResultTitle2.setText("제목: " + results.getJSONObject(i).getString("title"));
                lblResultWriter2.setText("작성자: " + results.getJSONObject(i).getString("name"));
                lblVisit2.setText("조회수: " + results.getJSONObject(i).getInt("visited"));
            } else if (i % 3 == 2) {
                lblResultTitle3.setText("제목: " + results.getJSONObject(i).getString("title"));
                lblResultWriter3.setText("작성자: " + results.getJSONObject(i).getString("name"));
                lblVisit3.setText("조회수: " + results.getJSONObject(i).getInt("visited"));
            }
        }
        
        if (end % 3 == 1) {
            jPanelResultList2.setVisible(false);
            jPanelResultList3.setVisible(false);
        } else if (end % 3 == 2) {
            jPanelResultList3.setVisible(false);
        }

        lblCurrentPage.setText(String.valueOf(currentPage)); // 현재 페이지 표시
    }

    // 다음 페이지 버튼 클릭 이벤트
    private void nextPage() {
        if (currentPage * itemsPerPage < results.length()) {
            currentPage++;
            updatePage();
        }
    }

    // 이전 페이지 버튼 클릭 이벤트
    private void previousPage() {
        if (currentPage > 1) {
            currentPage--;
            updatePage();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        lblCurrentPage = new javax.swing.JLabel();
        btnNextPage = new javax.swing.JButton();
        btnPrePage = new javax.swing.JButton();
        jPanelResultList1 = new javax.swing.JPanel();
        lblResultTitle1 = new javax.swing.JLabel();
        lblResultGrade1 = new javax.swing.JLabel();
        jPanelResultOrder1 = new javax.swing.JPanel();
        lblResultOrder1 = new javax.swing.JLabel();
        jPanelResultImg1 = new javax.swing.JPanel();
        lblResultWriter1 = new javax.swing.JLabel();
        btnResultBook1 = new javax.swing.JButton();
        lblResultCreate1 = new javax.swing.JLabel();
        lblVisit1 = new javax.swing.JLabel();
        jPanelResultList2 = new javax.swing.JPanel();
        lblResultTitle2 = new javax.swing.JLabel();
        lblResultGrade2 = new javax.swing.JLabel();
        jPanelResultOrder2 = new javax.swing.JPanel();
        lblResultOrder2 = new javax.swing.JLabel();
        jPanelResultImg2 = new javax.swing.JPanel();
        lblResultWriter2 = new javax.swing.JLabel();
        btnResultBook2 = new javax.swing.JButton();
        lblResultCreate2 = new javax.swing.JLabel();
        lblVisit2 = new javax.swing.JLabel();
        jPanelResultList3 = new javax.swing.JPanel();
        lblResultTitle3 = new javax.swing.JLabel();
        lblResultGrade3 = new javax.swing.JLabel();
        jPanelResultOrder3 = new javax.swing.JPanel();
        lblResultOrder3 = new javax.swing.JLabel();
        jPanelResultImg3 = new javax.swing.JPanel();
        lblResultWriter3 = new javax.swing.JLabel();
        btnResultBook3 = new javax.swing.JButton();
        lblResultCreate3 = new javax.swing.JLabel();
        lblVisit3 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        btnRecipeWrite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("레시피 공유 프로그램");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "제목", "작성자", "재료" }));

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnProfile.setText("내 정보");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblLogo)
                    .addGap(46, 46, 46)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                    .addComponent(btnProfile)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLogout)
                    .addContainerGap()))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLogo)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnProfile)
                        .addComponent(btnLogout)
                        .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblCurrentPage.setText("1");

        btnNextPage.setText(">");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        btnPrePage.setText("<");
        btnPrePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrePageActionPerformed(evt);
            }
        });

        jPanelResultList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblResultTitle1.setText("제목 : 김치");

        lblResultGrade1.setText("평점 : 0.0");

        lblResultOrder1.setText("1");

        javax.swing.GroupLayout jPanelResultOrder1Layout = new javax.swing.GroupLayout(jPanelResultOrder1);
        jPanelResultOrder1.setLayout(jPanelResultOrder1Layout);
        jPanelResultOrder1Layout.setHorizontalGroup(
            jPanelResultOrder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblResultOrder1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelResultOrder1Layout.setVerticalGroup(
            jPanelResultOrder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblResultOrder1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelResultImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelResultImg1Layout = new javax.swing.GroupLayout(jPanelResultImg1);
        jPanelResultImg1.setLayout(jPanelResultImg1Layout);
        jPanelResultImg1Layout.setHorizontalGroup(
            jPanelResultImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelResultImg1Layout.setVerticalGroup(
            jPanelResultImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        lblResultWriter1.setText("작성자 : 홍길동");

        btnResultBook1.setText("북마크");

        lblResultCreate1.setText("작성날짜 : 2025.01.01");

        lblVisit1.setText("조회수 : 0");

        javax.swing.GroupLayout jPanelResultList1Layout = new javax.swing.GroupLayout(jPanelResultList1);
        jPanelResultList1.setLayout(jPanelResultList1Layout);
        jPanelResultList1Layout.setHorizontalGroup(
            jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResultOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultTitle1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList1Layout.createSequentialGroup()
                        .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultWriter1)
                            .addComponent(lblResultGrade1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVisit1)
                            .addComponent(lblResultCreate1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultBook1)
                .addContainerGap())
        );
        jPanelResultList1Layout.setVerticalGroup(
            jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList1Layout.createSequentialGroup()
                        .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelResultList1Layout.createSequentialGroup()
                                .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultTitle1)
                                    .addComponent(lblVisit1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultGrade1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelResultList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultWriter1)
                                    .addComponent(lblResultCreate1)))
                            .addComponent(jPanelResultImg1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResultBook1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList1Layout.createSequentialGroup()
                        .addComponent(jPanelResultOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelResultList2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblResultTitle2.setText("제목 : 김치");

        lblResultGrade2.setText("평점 : 0.0");

        lblResultOrder2.setText("2");

        javax.swing.GroupLayout jPanelResultOrder2Layout = new javax.swing.GroupLayout(jPanelResultOrder2);
        jPanelResultOrder2.setLayout(jPanelResultOrder2Layout);
        jPanelResultOrder2Layout.setHorizontalGroup(
            jPanelResultOrder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblResultOrder2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelResultOrder2Layout.setVerticalGroup(
            jPanelResultOrder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblResultOrder2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelResultImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelResultImg2Layout = new javax.swing.GroupLayout(jPanelResultImg2);
        jPanelResultImg2.setLayout(jPanelResultImg2Layout);
        jPanelResultImg2Layout.setHorizontalGroup(
            jPanelResultImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelResultImg2Layout.setVerticalGroup(
            jPanelResultImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        lblResultWriter2.setText("작성자 : 홍길동");

        btnResultBook2.setText("북마크");

        lblResultCreate2.setText("작성날짜 : 2025.01.01");

        lblVisit2.setText("조회수 : 0");

        javax.swing.GroupLayout jPanelResultList2Layout = new javax.swing.GroupLayout(jPanelResultList2);
        jPanelResultList2.setLayout(jPanelResultList2Layout);
        jPanelResultList2Layout.setHorizontalGroup(
            jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResultOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultImg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultGrade2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList2Layout.createSequentialGroup()
                        .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultWriter2)
                            .addComponent(lblResultTitle2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVisit2)
                            .addComponent(lblResultCreate2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultBook2)
                .addContainerGap())
        );
        jPanelResultList2Layout.setVerticalGroup(
            jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList2Layout.createSequentialGroup()
                        .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelResultList2Layout.createSequentialGroup()
                                .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultTitle2)
                                    .addComponent(lblVisit2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultGrade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelResultList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultWriter2)
                                    .addComponent(lblResultCreate2)))
                            .addComponent(jPanelResultImg2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList2Layout.createSequentialGroup()
                        .addComponent(btnResultBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList2Layout.createSequentialGroup()
                        .addComponent(jPanelResultOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelResultList3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblResultTitle3.setText("제목 : 김치");

        lblResultGrade3.setText("평점 : 0.0");

        lblResultOrder3.setText("3");

        javax.swing.GroupLayout jPanelResultOrder3Layout = new javax.swing.GroupLayout(jPanelResultOrder3);
        jPanelResultOrder3.setLayout(jPanelResultOrder3Layout);
        jPanelResultOrder3Layout.setHorizontalGroup(
            jPanelResultOrder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblResultOrder3)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelResultOrder3Layout.setVerticalGroup(
            jPanelResultOrder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultOrder3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblResultOrder3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResultImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelResultImg3Layout = new javax.swing.GroupLayout(jPanelResultImg3);
        jPanelResultImg3.setLayout(jPanelResultImg3Layout);
        jPanelResultImg3Layout.setHorizontalGroup(
            jPanelResultImg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelResultImg3Layout.setVerticalGroup(
            jPanelResultImg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        lblResultWriter3.setText("작성자 : 홍길동");

        btnResultBook3.setText("북마크");

        lblResultCreate3.setText("작성날짜 : 2025.01.01");

        lblVisit3.setText("조회수 : 0");

        javax.swing.GroupLayout jPanelResultList3Layout = new javax.swing.GroupLayout(jPanelResultList3);
        jPanelResultList3.setLayout(jPanelResultList3Layout);
        jPanelResultList3Layout.setHorizontalGroup(
            jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResultOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultImg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultGrade3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultList3Layout.createSequentialGroup()
                        .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultWriter3)
                            .addComponent(lblResultTitle3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVisit3)
                            .addComponent(lblResultCreate3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultBook3)
                .addContainerGap())
        );
        jPanelResultList3Layout.setVerticalGroup(
            jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultList3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResultBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResultList3Layout.createSequentialGroup()
                        .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelResultOrder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelResultList3Layout.createSequentialGroup()
                                .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultTitle3)
                                    .addComponent(lblVisit3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultGrade3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelResultList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblResultWriter3)
                                    .addComponent(lblResultCreate3)))
                            .addComponent(jPanelResultImg3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblResult.setText("검색결과");

        btnRecipeWrite.setText("작성하기");
        btnRecipeWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipeWriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResultList3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResultList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResultList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(btnPrePage)
                                .addGap(18, 18, 18)
                                .addComponent(lblCurrentPage)
                                .addGap(18, 18, 18)
                                .addComponent(btnNextPage))
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(lblResult)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRecipeWrite)))
                .addContainerGap())
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult)
                .addGap(18, 18, 18)
                .addComponent(jPanelResultList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultList3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecipeWrite)
                .addGap(18, 18, 18)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentPage)
                    .addComponent(btnNextPage)
                    .addComponent(btnPrePage))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        sendSearchRequest();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void sendSearchRequest() {
        try {
            // HttpClient 객체 생성
            HttpClient client = HttpClient.newHttpClient();

            // 사용자가 선택한 검색 기준(제목 또는 재료) 가져오기
            String searchCriteria = comboSearch.getSelectedItem().toString(); // 콤보박스 선택 값
            String searchKeyword = txtSearch.getText().trim(); // 텍스트 필드에 입력된 검색어를 가져오고 공백 제거

            // 검색어가 비어 있는지 확인
            if (searchKeyword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "검색어를 입력해주세요.", "오류", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 검색 기준에 따른 파라미터 이름 설정
            String paramName;
            if ("제목".equals(searchCriteria)) {
                paramName = "title"; // 제목 검색
            } else if ("재료".equals(searchCriteria)) {
                paramName = "ingredient"; // 재료 검색
            } else {
                JOptionPane.showMessageDialog(this, "유효한 검색 기준이 아닙니다.", "오류", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 검색 요청 URL 생성
            String url = "https://m4srikufjgyzqbwltnujr7zyae0zlnrv.lambda-url.ap-northeast-2.on.aws/getUserRecipe?"
                    + paramName + "=" + URLEncoder.encode(searchKeyword, "UTF-8"); // 검색 키워드를 URL 인코딩

            // HttpRequest 객체 생성
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url)) // URL 설정
                    .GET() // GET 요청 설정
                    .header("Content-Type", "application/json") // Content-Type 헤더 추가
                    .header("Authorization", "Bearer " + TokenUtil.loadUserInfo().getString("token")) // 토큰 추가
                    .build();

            // 요청을 보내고 응답 받기
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            // 응답 상태 코드 확인
            if (response.statusCode() == 200) {
                // 응답 본문 가져오기
                String responseBody = response.body();
                System.out.println("검색 결과: " + responseBody);

                // JSON 응답 파싱
                JSONObject jsonResponse = new JSONObject(responseBody);
                String resultStatus = jsonResponse.getString("result");

                // 결과 상태 확인
                if ("success".equals(resultStatus)) {
                    // 검색 결과 배열 가져오기
                    JSONArray results = jsonResponse.getJSONArray("items");

                    // 검색 결과를 새 창에 전달하여 표시
                    SearchResultFrame resultFrame = new SearchResultFrame();
                    resultFrame.displayResults(results); // 결과 데이터를 설정
                    resultFrame.setVisible(true); // 새 창 열기
                    this.dispose(); // 현재 창 닫기
                } else {
                    // 결과 상태가 실패인 경우
                    JOptionPane.showMessageDialog(this, "검색 실패: 결과가 없습니다.", "정보", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                // 응답 상태 코드가 성공이 아닌 경우
                JOptionPane.showMessageDialog(this, "검색 실패: 서버 오류 발생", "오류", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            // 예외 발생 시 처리
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "검색 중 오류가 발생했습니다.", "오류", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        new SubFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        nextPage();
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnRecipeWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipeWriteActionPerformed
        // TODO add your handling code here:
        new WriteRecipeFrame().setVisible(true);
    }//GEN-LAST:event_btnRecipeWriteActionPerformed

    private void btnPrePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrePageActionPerformed
        previousPage();
    }//GEN-LAST:event_btnPrePageActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        new MyProfileFrame().setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchResultFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPrePage;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRecipeWrite;
    private javax.swing.JButton btnResultBook1;
    private javax.swing.JButton btnResultBook2;
    private javax.swing.JButton btnResultBook3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResultImg1;
    private javax.swing.JPanel jPanelResultImg2;
    private javax.swing.JPanel jPanelResultImg3;
    private javax.swing.JPanel jPanelResultList1;
    private javax.swing.JPanel jPanelResultList2;
    private javax.swing.JPanel jPanelResultList3;
    private javax.swing.JPanel jPanelResultOrder1;
    private javax.swing.JPanel jPanelResultOrder2;
    private javax.swing.JPanel jPanelResultOrder3;
    private javax.swing.JLabel lblCurrentPage;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultCreate1;
    private javax.swing.JLabel lblResultCreate2;
    private javax.swing.JLabel lblResultCreate3;
    private javax.swing.JLabel lblResultGrade1;
    private javax.swing.JLabel lblResultGrade2;
    private javax.swing.JLabel lblResultGrade3;
    private javax.swing.JLabel lblResultOrder1;
    private javax.swing.JLabel lblResultOrder2;
    private javax.swing.JLabel lblResultOrder3;
    private javax.swing.JLabel lblResultTitle1;
    private javax.swing.JLabel lblResultTitle2;
    private javax.swing.JLabel lblResultTitle3;
    private javax.swing.JLabel lblResultWriter1;
    private javax.swing.JLabel lblResultWriter2;
    private javax.swing.JLabel lblResultWriter3;
    private javax.swing.JLabel lblVisit1;
    private javax.swing.JLabel lblVisit2;
    private javax.swing.JLabel lblVisit3;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
